@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false


'hide footbox

participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "employeeRepository:\nEmployeeRepository" as EMPR
autonumber

 -> RepositorySingleton : getInstance()
        activate RepositorySingleton

           <-- RepositorySingleton  : repositories
        deactivate RepositorySingleton

         -> PLAT : getEmployeeRepository()
        activate PLAT

            <-- PLAT   : employeeRepository
        deactivate

         -> EMPR : getEmployeesOrderByName()
        activate EMPR

       <-- EMPR  : employeeList

@enduml