@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false


'hide footbox

participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "storeRepository:\nStoreRepository" as STRR
autonumber

 -> RepositorySingleton : getInstance()
        activate RepositorySingleton

            <-- RepositorySingleton  : repositories
        deactivate RepositorySingleton

         -> PLAT : getStoreRepository()
        activate PLAT

         <--   PLAT   : storeRepository
        deactivate PLAT

         -> STRR : getStoresOrderByProperty()
        activate STRR

            <-- STRR   : storeListSorted
            deactivate STRR

@enduml