@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

 autonumber

participant "dataIntegrityChecker:\nDataIntegrityChecker" as CHECKER
participant "purchaseOrderRepository:\nPurchaseOrderRepository" as POR
participant PO as "purchaseOrder:\nPurchaseOrder"

 -> CHECKER : submitPurchaseOrderData(purchaseOrderValues, announcement)
activate CHECKER
CHECKER -> POR : createPurchaseOrder(purchaseOrderValues, announcement)
activate POR
POR -> PO** : create(orderAmount, announcement, client, creationDate)

POR -> POR : add(purchaseOrder)
activate POR
POR -> POR : validatePurchaseOrder(purchaseOrder)
activate POR
POR --> POR:
deactivate POR
POR --> POR:
deactivate POR
POR --> CHECKER: purchaseOrder
deactivate POR

<-- CHECKER  : purchaseOrder
deactivate CHECKER

@enduml


