@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false



'hide footbox
participant ":AnnouncementController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "announcementRepository:\nAnnouncementRepository" as AR



     -> CTRL: createSMS (senderNumber, recipientNumber,dateAvailable, address, message)

    activate CTRL
    autonumber 18.1

            CTRL -> RepositorySingleton : getInstance()
                                    activate RepositorySingleton

                                        RepositorySingleton --> CTRL: repositories
                                    deactivate RepositorySingleton

                                    CTRL -> PLAT : getAnnouncementRepository()
                                    activate PLAT

                                        PLAT -> CTRL : announcementRepository
                                    deactivate PLAT

                                     CTRL -> AR: createSMS(senderNumber, recipientNumber,dateAvailable, address, message)

                                      activate AR

                                             AR -> AR: createSMS(senderNumber, recipientNumber,dateAvailable, address, message)
                                            activate AR



                                            AR --> AR


                                            deactivate AR
                                             AR--> CTRL : flag


                                             deactivate AR

                                             <--- CTRL : flag

                                             deactivate CTRL









@enduml