@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

hide circle
hide methods

class Address{
    streetAddress
    city
    state
    zipCode
}

class Property {
    price
    area
    distanceToCentre
}

class Photograph{
    uri
}

class Store{
    id
    designation
    adress
    email
    phoneNumber
}


class DataTime{
    date
}


class Inhabitable {
    bedroomNumber
    bathroomNumber
    parkingSpaces
    hasEquipment
}


class House {
    hasBasement
    hasLoft
    sunExposure
}



class PropertyType {
    description
}

class BusinessType {
    description
}
class UnregisteredUser {
}


class Announcement {
    announcementRequest
    listedPrice
    rentDuration
    agent
    date
    commission

}



UnregisteredUser "1" -- "*" Property : request >
Property "1" -- "1" Address : refers to <
Property "1" -- "1..30" Photograph : refers to <
Property "1"-- "1" Store : listed under <

Property "1" - "1" DataTime : refers to <
Property "1" <|-- "1" Inhabitable : has a

Inhabitable "1" <|-- "1" House : is a
PropertyType "1" -- "1" Property: cataloged as <
BusinessType "1" -- "*" Announcement: cataloged as <
Announcement "1" - "1" Property : listed under <

@enduml