@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title A

autonumber

'hide footbox
actor "Client UI" as CLN
participant ":CreateVisitRequestUI" as UI
participant ":CreateVisitRequestController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "Repositories\n:Repositories" as PLAT
participant "employeeRepository:\nEmployeeRepository" as AGTR
participant ":ApplicationSession" as _APP
participant "appSession\n:ApplicationSession" as APP
participant "currentSession\n:UserSession" as SESSION
participant "AnnouncementRepository:\AnnouncementRepository" as AR
participant "VisitRequestRepository:\VisitRequestRepository" as VRR
participant "VisitRequestMapper:\VisitRequestMapper" as VRM
participant "VisitRequestDTO:\VisitRequestDTO" as VRDTO
participant "VisitRequest:\VisitRequest" as VR
participant "clientRepository:\nClientRepository" as CLI

activate CLN

    CLN -> UI : asks to post a visit request

        activate UI

        UI -> CTRL** : CreateVisitRequestListController


        UI -> CTRL : getPropertyListByAnnouncement()
            activate CTRL


                CTRL -> RepositorySingleton : getInstance()

                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> PLAT : getAnnouncementRepository()
                activate PLAT

                    PLAT -> CTRL : AnnouncementRepository
                deactivate PLAT

                CTRL -> AR : getPropertyListByAnnouncement()
                activate AR


                   AR --> AR : getPropertyList()

                    AR --> CTRL : propertyListByAnnouncement



                deactivate AR


                CTRL-->UI : propertyListByAnnouncement

            deactivate CTRL

            UI --> CLN : show list of all properties and asks to select one
        deactivate UI

        CLN -> UI : select a property
        activate UI

            UI --> UI : keepData(property)


        UI --> CLN : request preferred date

        deactivate UI
        CLN -> UI : insert preferred date

        activate UI
            UI --> UI : keepData(preferredDate)

            UI --> UI : isValidDate(date);

        UI --> CLN : request time slot

        deactivate UI

        CLN -> UI : insert time slot

        activate UI

        UI --> UI : keepData(timeSlot)

        UI --> UI : isValidTimeSlot(timeSlot)





        UI --> CLN :  asks to confirmation to submit data

        deactivate UI

        CLN -> UI : confirmation to submit data
        activate UI

            UI -> CTRL : createVisitRequest(property, preferredDate,timeSlot)


                    activate CTRL

                        CTRL --> CTRL : getClientFromSession()

                        CTRL -> VRDTO** : new VisitRequestDTO(new PropertyDTO(property), new DateTimeDTO(preferredDate.getDate()), timeSlot,client.getName(), client.getPhoneNumber(), 0 );
                        activate VRDTO
                        VRDTO --> CTRL : visitRequestDTO
                        deactivate VRDTO

                        CTRL -> RepositorySingleton : getInstance()


                        activate RepositorySingleton

                        RepositorySingleton --> CTRL: repositories
                        deactivate RepositorySingleton

                        CTRL -> PLAT : getVisitRequestRepository()
                        activate PLAT

                        PLAT --> CTRL : RequestVisitRepository
                        deactivate PLAT


                         CTRL -> VRR :createVisitRequest(VisitRequestDTO)
                        activate VRR


                        VRR -> VRM :toEntity(VisitRequestDTO)
                        activate VRM

                        VRM --> VRDTO : propertyDTO = getProperty()
                        activate VRDTO
                        VRM --> VRM : convertPropertyDTOToProperty(propertyDTO)
                        deactivate VRDTO
                        VRM --> VRDTO : preferredDate = getPreferredDate()
                        activate VRDTO
                        VRM --> VRM : DateTimeDTOToDateformatted(preferredDate)
                        deactivate VRDTO
                        VRM --> VRDTO : timeSlot = getTimeSlot()
                        activate VRDTO
                        deactivate VRDTO
                        VRM --> VRDTO : clientName = getClientName()
                        activate VRDTO
                        deactivate VRDTO
                        VRM --> VRDTO : clientPhoneNumber = getClientPhoneNumber()
                        activate VRDTO
                        deactivate VRDTO


                       VRM --> VR** : create(property, preferredDate, timeSlot, clientName, clientPhoneNumber)

                       VRR --> VRR : validateVisitRequest (VisitRequestDTO)

                        VRR --> CTRL : wasAccepted
                        deactivate VRM
                        deactivate VRR

                    CTRL --> UI: wasAccepted
                    deactivate CTRL




         UI --> CLN : show success message and asks to add another time slot

        deactivate UI
        group loop [while confirm to add time slot]

        CLN -> UI : confirmation to submit another time slot

        activate UI

        UI --> CLN : request time slot

        deactivate UI

        CLN -> UI : insert time slot

        activate UI
                    UI --> UI : keepData(timeSlot)

        UI --> CLN : asks to confirmation to submit data
        deactivate UI


        CLN -> UI : confirmation to submit data

        activate UI

            UI -> CTRL :createVisitRequest(property, preferredDate,timeSlot)


            activate CTRL
                 CTRL --> CTRL : getClientFromSession()

                CTRL -> VRDTO** : new VisitRequestDTO(new PropertyDTO(property), new DateTimeDTO(preferredDate.getDate()), timeSlot,client.getName(), client.getPhoneNumber(), 0 );
                activate VRDTO
                VRDTO --> CTRL : visitRequestDTO
                deactivate VRDTO

                CTRL -> RepositorySingleton : getInstance()


                activate RepositorySingleton

                RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> PLAT : getVisitRequestRepository()
                activate PLAT

                PLAT --> CTRL : RequestVisitRepository
                deactivate PLAT


               CTRL -> VRR :createVisitRequest(VisitRequestDTO)
               activate VRR


               VRR -> VRM :toEntity(VisitRequestDTO)
               activate VRM

               VRM --> VRDTO : propertyDTO = getProperty()
               activate VRDTO
               VRM --> VRM : convertPropertyDTOToProperty(propertyDTO)
               deactivate VRDTO
               VRM --> VRDTO : preferredDate = getPreferredDate()
               activate VRDTO
               VRM --> VRM : DateTimeDTOToDateformatted(preferredDate)
               deactivate VRDTO
               VRM --> VRDTO : timeSlot = getTimeSlot()
               activate VRDTO
               deactivate VRDTO
               VRM --> VRDTO : clientName = getClientName()
               activate VRDTO
               deactivate VRDTO
               VRM --> VRDTO : clientPhoneNumber = getClientPhoneNumber()
               activate VRDTO
               deactivate VRDTO


              VRM --> VR** : create(property, preferredDate, timeSlot, clientName, clientPhoneNumber)

              VRR --> VRR : validateVisitRequest (VisitRequestDTO)

               VRR --> CTRL : wasAccepted
               deactivate VRM
               deactivate VRR

           CTRL --> UI: wasAccepted
           deactivate CTRL





             UI --> CLN : show success message and asks to add another time slot
        

        end

        group loop [while confirm to add date]
            
             UI --> CLN : asks to add another date
            deactivate UI

            CLN -> UI : confirmation to submit another date

                    activate UI

                    UI --> CLN : request date

                    deactivate UI

                    CLN -> UI : insert date

                    activate UI

                    UI --> UI : keepData(preferredDate)

                    UI --> UI : validateDate()

                    UI --> CLN : asks to confirmation to submit data



                    deactivate UI

                    CLN -> UI : confirmation to submit data

                    activate UI
                    UI -> CTRL :createVisitRequest(property, preferredDate,timeSlot)


                            activate CTRL
                                 CTRL --> CTRL : getClientFromSession()

                                CTRL -> VRDTO** : new VisitRequestDTO(new PropertyDTO(property), new DateTimeDTO(preferredDate.getDate()), timeSlot,client.getName(), client.getPhoneNumber(), 0 );
                                activate VRDTO
                                VRDTO --> CTRL : visitRequestDTO
                                deactivate VRDTO

                                CTRL -> RepositorySingleton : getInstance()


                                activate RepositorySingleton

                                RepositorySingleton --> CTRL: repositories
                                deactivate RepositorySingleton

                                CTRL -> PLAT : getVisitRequestRepository()
                                activate PLAT

                                PLAT --> CTRL : RequestVisitRepository
                                deactivate PLAT


                                CTRL -> VRR :createVisitRequest(VisitRequestDTO)
                                   activate VRR


                                   VRR -> VRM :toEntity(VisitRequestDTO)
                                   activate VRM

                                   VRM --> VRDTO : propertyDTO = getProperty()
                                   activate VRDTO
                                   VRM --> VRM : convertPropertyDTOToProperty(propertyDTO)
                                   deactivate VRDTO
                                   VRM --> VRDTO : preferredDate = getPreferredDate()
                                   activate VRDTO
                                   VRM --> VRM : DateTimeDTOToDateformatted(preferredDate)
                                   deactivate VRDTO
                                   VRM --> VRDTO : timeSlot = getTimeSlot()
                                   activate VRDTO
                                   deactivate VRDTO
                                   VRM --> VRDTO : clientName = getClientName()
                                   activate VRDTO
                                   deactivate VRDTO
                                   VRM --> VRDTO : clientPhoneNumber = getClientPhoneNumber()
                                   activate VRDTO
                                   deactivate VRDTO


                                  VRM --> VR** : create(property, preferredDate, timeSlot, clientName, clientPhoneNumber)

                                  VRR --> VRR : validateVisitRequest (VisitRequestDTO)

                                   VRR --> CTRL : wasAccepted
                                   deactivate VRM
                                   deactivate VRR

                               CTRL --> UI: wasAccepted
                               deactivate CTRL


                    UI --> CLN : show success message and asks to add another date or time slot

                    deactivate UI
                end

        deactivate UI


deactivate CLN

@enduml