@startuml
'https://plantuml.com/sequence-diagram
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false


autonumber 14


participant ":AnalyseDealsController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "Repositories\n:Repositories" as PLAT
participant "purchaseOrderRepository:\nPurchaseOrderRepository" as OR



-> CTRL: getDealsFromStore(store)
autonumber 14.1
    activate CTRL
     CTRL -> RepositorySingleton : getInstance()
    activate RepositorySingleton

        RepositorySingleton --> CTRL: repositories
    deactivate RepositorySingleton

    CTRL -> PLAT : getPurchaseOrderRepository()
    activate PLAT

        PLAT -> CTRL : PurchaseOrderRepository
    deactivate PLAT

    CTRL -> OR : getDealsByStore(store)
    activate OR
    OR --> CTRL : dealsList
    deactivate OR


    autonumber 15
    <-- CTRL  : dealsList
deactivate CTRL

@enduml