@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber 15

'hide footbox
participant ":RegisterEmployeeController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "employeeRepository:\nEmployeeRepository" as AGTR


     -> CTRL: getAgentsFromStore(store)

    activate CTRL

    autonumber 15.1
            CTRL -> RepositorySingleton : getInstance()
                                                        activate RepositorySingleton

                                                            RepositorySingleton --> CTRL: repositories
                                                        deactivate RepositorySingleton

                                                        CTRL -> PLAT : getEmployeeRepository()
                                                        activate PLAT

                                                            PLAT -> CTRL : employeeRepository
                                                        deactivate PLAT

                                                        CTRL -> AGTR : getAgentsFromStore(store)
                                                        activate AGTR

                                                            AGTR --> CTRL : agentsList
                                                        deactivate AGTR



    autonumber 16

    <-- CTRL  : agentsList

    deactivate CTRL


@enduml