@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber 62

'hide footbox
participant "store:\nStore" as STR
participant "AnnouncementRequest" as ANR


     -> STR: createAnnouncementRequest(businessType, property, agent, client)
                                                                       activate STR

    autonumber 62.1
            STR -> ANR**: create(businessType, property, agent, client)

                               STR -> STR: addAnnouncement(announcementRequest)
                               activate STR
                                   STR -> STR: validateAnnouncement(announcementRequest)
                                   activate STR
                                       STR --> STR
                                   deactivate STR
                                   STR --> STR



    autonumber 63

    <-- STR  : announcementRequest

    deactivate STR


@enduml