@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false


autonumber 12

participant "StoreRepository\n:Employee" as REP
participant "store:\nStore" as Str
        -> REP: createStore( id,  designation,  email, storeAddress, phoneNumber)
                    activate REP

                    autonumber 12.1

                       REP -> Str** : new Store(id,designation,email,address,phoneNumber)

                        REP -> REP: storeClone.clone()


                       activate REP
                           REP -> REP: add(storeClone);
                           activate REP
                               REP --> REP
                           deactivate REP

                           REP --> REP
                       deactivate REP

                    autonumber 13
                    <-- REP: storeClone

@enduml