@startuml
'https://plantuml.com/sequence-diagram

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false


autonumber 3

participant ":ReplyToAgentAboutVisitRequestController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "Repositories\n:Repositories" as PLAT
participant "VisitRequestRepository:\VisitRequestRepository" as VRR

 -> CTRL :  GetVisitRequests()

        activate CTRL
        CTRL -> RepositorySingleton : getInstance()


                    activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                    deactivate RepositorySingleton

                    CTRL -> PLAT : getVisitRequestRepository()
                    activate PLAT

                    PLAT --> CTRL : RequestVisitRepository
                    deactivate PLAT


                    CTRL -> VRR :getVisitRequest
                    activate VRR

                    VRR --> VRR : getVisitRequestAccepted()


                    VRR --> CTRL : VisitRequests
                    deactivate VRR


                    <-- CTRL : VisitRequests
                    deactivate CTRL
                    @enduml