@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false


autonumber 73

participant ":PlaceOrderController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "propertyRepository:\nPropertyRepository" as PR
participant ":ApplicationSession" as _APP
participant "appSession\n:ApplicationSession" as APP
participant "currentSession\n:UserSession" as SESSION
participant "clientRepository:\nClientRepository" as CLI
participant "purchaseOrderRepository:\nPurchaseOrderRepository" as OR
participant "purchaseOrderMapper:\nPurchaseOrderMapper" as POMAP
participant "PurchaseOrderDTO" as PODTO
participant "PurchaseOrder" as OFF

group Create Purchase Order
        --> CTRL : placeOrder(orderAmount, propertyDescription)
                 activate CTRL

                     CTRL -> RepositorySingleton : getInstance()
                     activate RepositorySingleton

                         RepositorySingleton --> CTRL: repositories
                     deactivate RepositorySingleton

                     CTRL -> PLAT : getPropertyRepository()
                     activate PLAT

                         PLAT --> CTRL : propertyRepository
                     deactivate PLAT

                     CTRL -> PR : getPropertyByDescription(propertyDescription)
                     activate PR

                         PR --> CTRL : property
                     deactivate PR

                     CTRL -> PR : getSaleAnnouncementByProperty(property)
                     activate PR

                         PR --> CTRL : announcement
                     deactivate PR

                     CTRL -> _APP: getInstance()
                      activate _APP
                          _APP --> CTRL: appSession
                      deactivate _APP


                      CTRL -> APP: getCurrentSession()
                      activate APP

                          APP --> CTRL: currentSession
                      deactivate APP

                      CTRL -> SESSION: email = getUserEmail()
                      activate SESSION

                          SESSION --> CTRL: email
                      deactivate SESSION


                      CTRL -> PLAT : getClientRepository()
                      activate PLAT

                          PLAT --> CTRL : clientRepository
                      deactivate PLAT
                      CTRL -> CLI: client = getClientByEmail(email)
                      activate CLI

                          CLI --> CTRL : client
                      deactivate CLI
                     CTRL -> PLAT : getPurchaseOrderRepository()
                     activate PLAT

                         PLAT --> CTRL : purchaseOrderRepository
                     deactivate PLAT
                     CTRL -> OR : placeOrder(orderAmount, propertyDescription, client)
                     activate OR
                         OR -> OFF** : create(orderAmount, announcement, client)
                         OR -> OR: addOffer(order)
                        activate OR
                            OR -> OR: validateOffer(order)
                            activate OR
                                OR --> OR
                            deactivate OR
                            OR --> OR

                         deactivate OR

                         OR --> CTRL : order
                     deactivate OR
                    <-- CTRL : order
                 deactivate CTRL
end group
@enduml