@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title As an Agent, I want to list real estate purchase orders to accept or decline a purchase order for a property

autonumber

actor "Agent" as AGT
participant ":PurchaseOrdersUI" as UI
participant ":PurchaseOrdersController" as CTRL



activate AGT

    AGT -> UI : asks to list purchase orders

        activate UI

            UI -> CTRL** : create

            UI->CTRL : getPropertiesAndOffers(AnnouncementComparator, BuyOrderComparator)


                activate CTRL
                 CTRL --> CTRL :getSaleAnnouncements()
                 CTRL --> CTRL : getListOldestToNewest(announcementList,AnnouncementComparator)

                CTRL --> UI : announcementList

                deactivate CTRL

                UI-> CTRL : getOrders(saleAnnouncement, BuyOrderComparator)

                activate CTRL

                 CTRL -->CTRL: getBuyOrders(saleAnnouncement)



                 CTRL --> CTRL : getListDescendingOrder(buyOrdersList,BuyOrderComparator)

                autonumber 4
                CTRL-->UI : itemListSorted
                deactivate CTRL



'

            UI --> AGT : provide properties list and respective offers
        deactivate UI

    group loop
    AGT -> UI : selectes property and offer
    activate UI

        UI -> UI : selectBuyOrder()
        activate UI

        UI->UI : ValidateInput()
        deactivate UI


    UI--> AGT : asks if is to accept or decline offer
    deactivate UI
    end

    group loop
    AGT -> UI : submit answer
    activate UI

        UI -> UI : submitAnswer()
        activate UI

        UI->UI : ValidateAnswer()
        deactivate UI

        end

        UI --> CTRL : createEmail()
        activate CTRL

        ref over CTRL
        create email
        end ref

        CTRL --> UI: message
        deactivate CTRL

    UI --> AGT: displays operation success and send email to client
    deactivate UI


deactivate AGT

@enduml