@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber 15

'hide footbox
participant ":RegisterEmployeeController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "storeRepository:\nStoreRepository" as STRR


     --> CTRL: getStoreByDescription(storeDescription)

    activate CTRL

    autonumber 15.1
        CTRL -> RepositorySingleton : getInstance()
        activate RepositorySingleton

            RepositorySingleton --> CTRL: repositories
        deactivate RepositorySingleton

        CTRL -> PLAT : getStoreRepository()
        activate PLAT

            PLAT -> CTRL : storeRepository
        deactivate PLAT

        CTRL -> STRR : getStoreByDescription(storeDescription)
        activate STRR

            STRR --> CTRL : store
        deactivate STRR


    autonumber 16

    <-- CTRL  : store

    deactivate CTRL


@enduml